apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.cluster }}
  project: {{ .Values.project }}
  source:
    chart: 
    helm:
      valueFiles:
      - values.yaml
      - cluster-autoscaler.yaml
    repoURL: https://kubernetes-charts.storage.googleapis.com/
    targetRevision: 1.16.4
